name: Release

on:
  workflow_dispatch:

permissions: {}

jobs:
  trigger:
    name: Trigger release in bitwarden/deploy
    runs-on: ubuntu-24.04
    environment: mcp-server-release
    permissions:
      contents: read
      deployments: write
      id-token: write
    steps:
      - name: Check branch
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/main" ]]; then
            echo "==================================================="
            echo "[!] Can only trigger release from the 'main' branch"
            echo "==================================================="
            exit 1
          fi

      - name: Trigger release in bitwarden/deploy
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: release-mcp-server
